Repository swiftlang/swift-tools-support-core, pull requests merged in 2021-12, with the labels that each got.

#266 deprecate PkgConfig
  Sources/TSCUtility/PkgConfig.swift
  Tests/TSCUtilityTests/PkgConfigParserTests.swift
Labels: ready

#272 [5.6] TSCBasic: properly track abnormal exits on Windows
  Sources/TSCBasic/Process.swift
Labels: 5.6

#274 abstract SHA256 implementaiton differences behind a single implementation
  Sources/TSCBasic/HashAlgorithms.swift
  Tests/TSCBasicTests/SHA256Tests.swift
Labels: ready

#273 store lock files in temporary directory
  Sources/TSCBasic/FileSystem.swift
  Sources/TSCBasic/Lock.swift
  Sources/TSCBasic/TemporaryFile.swift
  Tests/TSCBasicTests/LockTests.swift
Labels: ready

#275 [5.6] store lock files in temporary directory (#273)
  Sources/TSCBasic/FileSystem.swift
  Sources/TSCBasic/Lock.swift
  Sources/TSCBasic/TemporaryFile.swift
  Tests/TSCBasicTests/LockTests.swift
Labels: ready, 5.6
