Repository swiftlang/swift-tools-support-core, pull requests merged in 2023-12, with the labels that each got.

#450 Use a concurrent queue to wait for process completion
  Sources/TSCBasic/CMakeLists.txt
  Sources/TSCBasic/Process/Process.swift
  Sources/TSCBasic/Process/ProcessEnv.swift
  Sources/TSCBasic/Process/ProcessSet.swift
Labels: concurrency, bug

#453 TSCBasic: deprecate `ProcessSet`
  Sources/TSCBasic/Process/ProcessSet.swift
  Tests/TSCBasicTests/ProcessSetTests.swift
  Tests/TSCBasicTests/ProcessTests.swift
Labels: deprecation

#454 TSCBasic: remove some deprecated interfaces in `Process`
  Sources/TSCBasic/Process/Process.swift
Labels: deprecation

#447 TSCBasic: support case insensitivity for environment
  Sources/TSCBasic/FileSystem.swift
  Sources/TSCBasic/Process/Process.swift
  Sources/TSCBasic/Process/ProcessEnv.swift
  Tests/TSCBasicTests/ProcessEnvTests.swift
Labels: bug
